### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by jonauq2508** [NetFlora/Netflora#1]
Hi.
I am wondering if this code is open and if yes, How to run it! thanks in advance

**Comment by karasinski-mauro** [comment]
Hi @jonauq2508 

Yes, the code is open-source, and you can use Google Colab to run it (click on the 'Open in Colab' button).

I recommend taking our course, which you can find under 'Useful Links.' Unfortunately, the course is currently only available in Portuguese. However, if you watch the videos on YouTube, you can enable automatic subtitles. The course is free, enjoy!

**Comment by jonauq2508** [comment]
great, thank you very much for your answer
